# Generated by Django 2.1.1 on 2019-09-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0005_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=True, verbose_name='Is send')),
                ('status', models.CharField(choices=[('n', 'No'), ('s', 'Send')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
