# Generated by Django 2.1.1 on 2019-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0006_mtemplate_sendmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtemplate',
            name='status',
            field=models.CharField(choices=[('n', 'No'), ('s', 'send_message')], default='n', max_length=1),
        ),
    ]
