# Generated by Django 2.1.1 on 2019-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0008_auto_20190927_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendMessage',
        ),
        migrations.AlterField(
            model_name='mtemplate',
            name='status',
            field=models.CharField(choices=[('n', 'No'), ('s', 'sended')], default='n', max_length=1),
        ),
    ]
