# Generated by Django 2.1.1 on 2019-10-02 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BafosApp', '0011_auto_20190930_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTracking',
            new_name='HistoricalPolls',
        ),
        migrations.RenameModel(
            old_name='Tracking',
            new_name='Polls',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AlterModelOptions(
            name='historicalpolls',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical polls'},
        ),
    ]
