# Generated by Django 2.1.1 on 2019-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0012_auto_20191002_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtemplate',
            name='slug',
            field=models.CharField(default='default_slug', max_length=50, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='mtemplate',
            name='name',
            field=models.CharField(default='default_name', max_length=50, verbose_name='Name'),
        ),
    ]
