# Generated by Django 2.1.1 on 2019-10-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0013_auto_20191007_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpolls',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Poll'},
        ),
        migrations.AlterModelOptions(
            name='mtemplate',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
    ]
